/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as ExpertisesRouteImport } from './routes/expertises'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as RealisationsIndexRouteImport } from './routes/realisations.index'
import { Route as RealisationsSlugRouteImport } from './routes/realisations.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesRoute = ExpertisesRouteImport.update({
  id: '/expertises',
  path: '/expertises',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsIndexRoute = RealisationsIndexRouteImport.update({
  id: '/realisations/',
  path: '/realisations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsSlugRoute = RealisationsSlugRouteImport.update({
  id: '/realisations/$slug',
  path: '/realisations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/expertises': typeof ExpertisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/expertises': typeof ExpertisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/realisations': typeof RealisationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/expertises': typeof ExpertisesRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/realisations/$slug': typeof RealisationsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/realisations/': typeof RealisationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/expertises'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/blog/'
    | '/realisations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/expertises'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/blog'
    | '/realisations'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/equipements'
    | '/expertises'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/blog/$slug'
    | '/realisations/$slug'
    | '/blog/'
    | '/realisations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  EquipementsRoute: typeof EquipementsRoute
  ExpertisesRoute: typeof ExpertisesRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  BlogSlugRoute: typeof BlogSlugRoute
  RealisationsSlugRoute: typeof RealisationsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  RealisationsIndexRoute: typeof RealisationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises': {
      id: '/expertises'
      path: '/expertises'
      fullPath: '/expertises'
      preLoaderRoute: typeof ExpertisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/': {
      id: '/realisations/'
      path: '/realisations'
      fullPath: '/realisations/'
      preLoaderRoute: typeof RealisationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations/$slug': {
      id: '/realisations/$slug'
      path: '/realisations/$slug'
      fullPath: '/realisations/$slug'
      preLoaderRoute: typeof RealisationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  EquipementsRoute: EquipementsRoute,
  ExpertisesRoute: ExpertisesRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  BlogSlugRoute: BlogSlugRoute,
  RealisationsSlugRoute: RealisationsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  RealisationsIndexRoute: RealisationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
